owner: LIGUE-CENTRE-VAL-DE-LOIRE-DE-NATATION
repo: swimo-upptime

sites:
  - name: Admin
    url: https://swimo-v2.natation-cvl.fr/
  - name: Api
    url: https://swimo-v2.natation-cvl.fr/api/articles?page=1
    headers:
      - "accept: application/ld+json"

assignees:
  - dferdoille

status-website:
  baseUrl: /swimo-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Swimo Upptime
  introTitle: "Check **Swim'O BO & APIs** status."
  introMessage: Swim'O Status page
  navbar:
    - title: Status
      href: /
